// Generated by CoffeeScript 1.10.0
(function() {
  var CommonJsHandler, Promise, fs, path, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  fs = require('fs');

  path = require('path');

  Promise = require('bluebird');

  util = require('util');

  module.exports = CommonJsHandler = (function() {
    function CommonJsHandler(template) {
      this.template = template;
      this.handleFile = bind(this.handleFile, this);
      if (this.template == null) {
        this.template = 'function () {\nvar module = {};\n(function () {\n\n%s\n}).call(this);\nreturn module.exports.apply(this, arguments);\n}';
      }
    }

    CommonJsHandler.prototype.handleFile = function(filePath) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          if (path.extname(filePath) !== '.js') {
            return resolve(null);
          }
          return fs.readFile(filePath, function(error, data) {
            if (error) {
              return reject(error);
            }
            resolve([path.basename(filePath, '.js'), util.format(_this.template, data.toString())]);
          });
        };
      })(this));
    };

    return CommonJsHandler;

  })();

}).call(this);
