// Generated by CoffeeScript 1.10.0
(function() {
  var CommonCoffeeHandler, Promise, coffee, fs, path, util,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  coffee = require('coffee-script');

  fs = require('fs');

  path = require('path');

  Promise = require('bluebird');

  util = require('util');

  module.exports = CommonCoffeeHandler = (function() {
    function CommonCoffeeHandler(template) {
      this.template = template;
      this.handleFile = bind(this.handleFile, this);
      if (this.template == null) {
        this.template = 'function () {\nvar module = {};\n\n%s\nreturn module.exports.apply(this, arguments);\n}';
      }
    }

    CommonCoffeeHandler.prototype.handleFile = function(filePath) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          if (path.extname(filePath) !== '.coffee') {
            return resolve(null);
          }
          return fs.readFile(filePath, function(error, data) {
            var error1, js;
            if (error) {
              return reject(error);
            }
            try {
              js = coffee.compile(data.toString());
            } catch (error1) {
              error = error1;
              return reject(error);
            }
            resolve([path.basename(filePath, '.coffee'), util.format(_this.template, js)]);
          });
        };
      })(this));
    };

    return CommonCoffeeHandler;

  })();

}).call(this);
