// Generated by CoffeeScript 1.10.0
(function() {
  var HandlerError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = HandlerError = (function(superClass) {
    extend(HandlerError, superClass);

    function HandlerError(handlerName, filename, cause) {
      this.handlerName = handlerName;
      this.filename = filename;
      this.cause = cause;
      this.message = this.handlerName + " could not process '" + this.filename + "'.";
    }

    HandlerError.prototype.toString = function() {
      var string;
      string = this.message;
      if (this.cause) {
        string += " Caused by:\n\n" + (this.cause.toString());
      }
      return string;
    };

    return HandlerError;

  })(Error);

}).call(this);
